--------------------------------------------------------
--  Constraints for Table ACTIVITY_RULE_GROUPS
--------------------------------------------------------

  ALTER TABLE "KMS"."ACTIVITY_RULE_GROUPS" MODIFY ("RULEGROUPID" NOT NULL ENABLE);
 
  ALTER TABLE "KMS"."ACTIVITY_RULE_GROUPS" MODIFY ("RULEGROUPNAMECN" NOT NULL ENABLE);
 
  ALTER TABLE "KMS"."ACTIVITY_RULE_GROUPS" ADD PRIMARY KEY ("RULEGROUPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "KMS"."ACTIVITY_RULE_GROUPS" ADD UNIQUE ("RULEGROUPNAMECN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "KMS"."ACTIVITY_RULE_GROUPS" MODIFY ("CREATEUSER" NOT NULL ENABLE);
 
  ALTER TABLE "KMS"."ACTIVITY_RULE_GROUPS" MODIFY ("CREATETIME" NOT NULL ENABLE);
 
  ALTER TABLE "KMS"."ACTIVITY_RULE_GROUPS" MODIFY ("ISEXCLUSIVE" NOT NULL ENABLE);
 
  ALTER TABLE "KMS"."ACTIVITY_RULE_GROUPS" MODIFY ("ISCOMMONGROUP" NOT NULL ENABLE);
 
  ALTER TABLE "KMS"."ACTIVITY_RULE_GROUPS" MODIFY ("RULEGROUPWEIGHT" NOT NULL ENABLE);
 
  ALTER TABLE "KMS"."ACTIVITY_RULE_GROUPS" MODIFY ("RULEGROUPNAMEEN" NOT NULL ENABLE);
