--------------------------------------------------------
--  DDL for Table ACTIVITY_RULE_GROUPS
--------------------------------------------------------

  CREATE TABLE "KMS"."ACTIVITY_RULE_GROUPS" 
   (	"RULEGROUPID" NUMBER, 
	"RULEGROUPNAMECN" VARCHAR2(50 BYTE), 
	"RULEGROUPWEIGHT" NUMBER(*,0) DEFAULT 0, 
	"CREATEUSER" VARCHAR2(50 BYTE), 
	"CREATETIME" TIMESTAMP (6) DEFAULT NULL, 
	"ISEXCLUSIVE" NUMBER DEFAULT 0, 
	"RULEGROUPNAMEEN" VARCHAR2(50 BYTE), 
	"ISCOMMONGROUP" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
