--------------------------------------------------------
--  DDL for Table ACTIVITY_FORM_ATTR_INFO
--------------------------------------------------------

  CREATE TABLE "KMS"."ACTIVITY_FORM_ATTR_INFO" 
   (	"FORMATTRINFOID" NUMBER, 
	"FORMATTRNAME" VARCHAR2(40 BYTE), 
	"FORMATTRNAMELABEL" VARCHAR2(30 BYTE), 
	"FORMATTRNAMEDEFAULTVALUE" VARCHAR2(100 BYTE), 
	"FORMATTRNAMEVALIDATION" VARCHAR2(100 BYTE), 
	"FORMATTRNAMETYPE" VARCHAR2(30 BYTE), 
	"FORMATTRNAMEFILLTYPE" VARCHAR2(30 BYTE), 
	"CREATEUSER" VARCHAR2(40 BYTE), 
	"CREATETIME" TIMESTAMP (6), 
	"HASREPLYFORFORMATTR" NUMBER, 
	"EXRULEGROUPID" NUMBER, 
	"RULEIDS" VARCHAR2(500 BYTE), 
	"FORMATTRINTRODUCE" VARCHAR2(500 BYTE), 
	"FORMNAMETYPEATTRS" VARCHAR2(1000 BYTE), 
	"ORDERFORFORM" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
